steps:
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - functions
      - deploy
      - apply_some_solver
      - --runtime=python38
      - --region=asia-northeast1
      - --trigger-http
      - --allow-unauthenticated
    waitFor: ["-"]
timeout: 1200s
