steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - functions
      - deploy
      - apply_some_solver
      - --runtime=python39
      - --region=asia-northeast1
      - --trigger-http
      - --source=.
      - --allow-unauthenticated
    waitFor: ["-"]
timeout: 1200s
