steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/python-template/app:$COMMIT_SHA",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/python-template/app:$COMMIT_SHA",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - run
      - deploy
      - example
      - --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/python-template/app:$COMMIT_SHA
      - --region=asia-northeast1
      - --platform=managed
      - --allow-unauthenticated
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - gcloud
      - workflows
      - deploy
      - python-template
      - --source=workflows.yaml
      - --location=asia-southeast1
    waitFor: ["-"]
timeout: 1200s
images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/python-template/app:$COMMIT_SHA
