# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solver.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='solver.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\026institute.besna.solverB\013SolverProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csolver.proto\".\n\rSolverRequest\x12\x0f\n\x07\x61piName\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"@\n\x0bSolverReply\x12\x0f\n\x07\x61piName\x18\x01 \x01(\t\x12\x12\n\napiVersion\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"Y\n\x0bSolverError\x12\x0f\n\x07\x61piName\x18\x01 \x01(\t\x12\x12\n\napiVersion\x18\x02 \x01(\t\x12\x0f\n\x07\x65rrorId\x18\x03 \x01(\t\x12\x14\n\x0c\x65rrorMessage\x18\x04 \x01(\t\"Z\n\x0eSolverResponse\x12\x1d\n\x05reply\x18\x01 \x01(\x0b\x32\x0c.SolverReplyH\x00\x12\x1d\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x0c.SolverErrorH\x00\x42\n\n\x08response2\x9c\x02\n\rSolverService\x12\x36\n\x11\x41nalyzeOnUnaryRPC\x12\x0e.SolverRequest\x1a\x0f.SolverResponse\"\x00\x12\x42\n\x1b\x41nalyzeOnServerStreamingRPC\x12\x0e.SolverRequest\x1a\x0f.SolverResponse\"\x00\x30\x01\x12\x42\n\x1b\x41nalyzeOnClientStreamingRPC\x12\x0e.SolverRequest\x1a\x0f.SolverResponse\"\x00(\x01\x12K\n\"AnalyzeOnBidirectionalStreamingRPC\x12\x0e.SolverRequest\x1a\x0f.SolverResponse\"\x00(\x01\x30\x01\x42\'\n\x16institute.besna.solverB\x0bSolverProtoP\x01\x62\x06proto3'
)




_SOLVERREQUEST = _descriptor.Descriptor(
  name='SolverRequest',
  full_name='SolverRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiName', full_name='SolverRequest.apiName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='SolverRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=62,
)


_SOLVERREPLY = _descriptor.Descriptor(
  name='SolverReply',
  full_name='SolverReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiName', full_name='SolverReply.apiName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='SolverReply.apiVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='SolverReply.text', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=64,
  serialized_end=128,
)


_SOLVERERROR = _descriptor.Descriptor(
  name='SolverError',
  full_name='SolverError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='apiName', full_name='SolverError.apiName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='apiVersion', full_name='SolverError.apiVersion', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorId', full_name='SolverError.errorId', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='errorMessage', full_name='SolverError.errorMessage', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=219,
)


_SOLVERRESPONSE = _descriptor.Descriptor(
  name='SolverResponse',
  full_name='SolverResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply', full_name='SolverResponse.reply', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='SolverResponse.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='SolverResponse.response',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=221,
  serialized_end=311,
)

_SOLVERRESPONSE.fields_by_name['reply'].message_type = _SOLVERREPLY
_SOLVERRESPONSE.fields_by_name['error'].message_type = _SOLVERERROR
_SOLVERRESPONSE.oneofs_by_name['response'].fields.append(
  _SOLVERRESPONSE.fields_by_name['reply'])
_SOLVERRESPONSE.fields_by_name['reply'].containing_oneof = _SOLVERRESPONSE.oneofs_by_name['response']
_SOLVERRESPONSE.oneofs_by_name['response'].fields.append(
  _SOLVERRESPONSE.fields_by_name['error'])
_SOLVERRESPONSE.fields_by_name['error'].containing_oneof = _SOLVERRESPONSE.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['SolverRequest'] = _SOLVERREQUEST
DESCRIPTOR.message_types_by_name['SolverReply'] = _SOLVERREPLY
DESCRIPTOR.message_types_by_name['SolverError'] = _SOLVERERROR
DESCRIPTOR.message_types_by_name['SolverResponse'] = _SOLVERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SolverRequest = _reflection.GeneratedProtocolMessageType('SolverRequest', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERREQUEST,
  '__module__' : 'solver_pb2'
  # @@protoc_insertion_point(class_scope:SolverRequest)
  })
_sym_db.RegisterMessage(SolverRequest)

SolverReply = _reflection.GeneratedProtocolMessageType('SolverReply', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERREPLY,
  '__module__' : 'solver_pb2'
  # @@protoc_insertion_point(class_scope:SolverReply)
  })
_sym_db.RegisterMessage(SolverReply)

SolverError = _reflection.GeneratedProtocolMessageType('SolverError', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERERROR,
  '__module__' : 'solver_pb2'
  # @@protoc_insertion_point(class_scope:SolverError)
  })
_sym_db.RegisterMessage(SolverError)

SolverResponse = _reflection.GeneratedProtocolMessageType('SolverResponse', (_message.Message,), {
  'DESCRIPTOR' : _SOLVERRESPONSE,
  '__module__' : 'solver_pb2'
  # @@protoc_insertion_point(class_scope:SolverResponse)
  })
_sym_db.RegisterMessage(SolverResponse)


DESCRIPTOR._options = None

_SOLVERSERVICE = _descriptor.ServiceDescriptor(
  name='SolverService',
  full_name='SolverService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=598,
  methods=[
  _descriptor.MethodDescriptor(
    name='AnalyzeOnUnaryRPC',
    full_name='SolverService.AnalyzeOnUnaryRPC',
    index=0,
    containing_service=None,
    input_type=_SOLVERREQUEST,
    output_type=_SOLVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeOnServerStreamingRPC',
    full_name='SolverService.AnalyzeOnServerStreamingRPC',
    index=1,
    containing_service=None,
    input_type=_SOLVERREQUEST,
    output_type=_SOLVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeOnClientStreamingRPC',
    full_name='SolverService.AnalyzeOnClientStreamingRPC',
    index=2,
    containing_service=None,
    input_type=_SOLVERREQUEST,
    output_type=_SOLVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AnalyzeOnBidirectionalStreamingRPC',
    full_name='SolverService.AnalyzeOnBidirectionalStreamingRPC',
    index=3,
    containing_service=None,
    input_type=_SOLVERREQUEST,
    output_type=_SOLVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SOLVERSERVICE)

DESCRIPTOR.services_by_name['SolverService'] = _SOLVERSERVICE

# @@protoc_insertion_point(module_scope)
