# generated by datamodel-codegen:
#   filename:  metadata.json
#   timestamp: 2021-07-26T09:17:36+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field


class SchemaOfSolverMetadata(BaseModel):
    __root__: Any = Field(..., title='Schema of Solver metadata')


class ApiName(BaseModel):
    __root__: str = Field(..., description='API name', regex='^Solver$', title='API Name')


class ApiVersion(BaseModel):
    __root__: str = Field(
        ..., description='API version', regex='^[0-9]+\\.[0-9]+\\.[0-9]+((M|RC)-[0-9]+)*$', title='API Version'
    )
