# generated by datamodel-codegen:
#   filename:  output.json
#   timestamp: 2021-07-26T09:17:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class ApiName(BaseModel):
    __root__: str = Field(..., description='API name', regex='^Solver$', title='API Name')


class ApiVersion(BaseModel):
    __root__: str = Field(
        ..., description='API version', regex='^[0-9]+\\.[0-9]+\\.[0-9]+((M|RC)-[0-9]+)*$', title='API Version'
    )


class SchemaOfSolverOutput(BaseModel):
    apiName: ApiName
    apiVersion: ApiVersion
    text: str = Field(..., description='text', min_length=1, title='Text')
