# generated by datamodel-codegen:
#   filename:  error.json
#   timestamp: 2021-07-26T08:07:36+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ApiName(BaseModel):
    __root__: constr(regex=r'^Solver$') = Field(..., description='API name', title='API Name')


class ApiVersion(BaseModel):
    __root__: constr(regex=r'^[0-9]+\.[0-9]+\.[0-9]+((M|RC)-[0-9]+)*$') = Field(
        ..., description='API version', title='API Version'
    )


class SchemaOfSolverError(BaseModel):
    apiName: ApiName
    apiVersion: ApiVersion
    errorId: constr(regex=r'^error:.+$') = Field(..., description='error ID', title='Error ID')
    errorMessage: str = Field(..., description='error message', title='Error Message')
