# generated by datamodel-codegen:
#   filename:  metadata.json
#   timestamp: 2021-07-26T08:07:35+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field, constr


class SchemaOfSolverMetadata(BaseModel):
    __root__: Any = Field(..., title='Schema of Solver metadata')


class ApiName(BaseModel):
    __root__: constr(regex=r'^Solver$') = Field(..., description='API name', title='API Name')


class ApiVersion(BaseModel):
    __root__: constr(regex=r'^[0-9]+\.[0-9]+\.[0-9]+((M|RC)-[0-9]+)*$') = Field(
        ..., description='API version', title='API Version'
    )
