# generated by datamodel-codegen:
#   filename:  output.json
#   timestamp: 2021-07-26T08:07:37+00:00

from __future__ import annotations

from pydantic import BaseModel, Field, constr


class ApiName(BaseModel):
    __root__: constr(regex=r'^Solver$') = Field(..., description='API name', title='API Name')


class ApiVersion(BaseModel):
    __root__: constr(regex=r'^[0-9]+\.[0-9]+\.[0-9]+((M|RC)-[0-9]+)*$') = Field(
        ..., description='API version', title='API Version'
    )


class SchemaOfSolverOutput(BaseModel):
    apiName: ApiName
    apiVersion: ApiVersion
    text: constr(min_length=1) = Field(..., description='text', title='Text')
