from enum import Enum, unique


@unique
class Color(Enum):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Color - a model defined in OpenAPI

        members:
            RED
            GREEN
            BLUE
    """

    RED = "RED"
    GREEN = "GREEN"
    BLUE = "BLUE"
