from dataclasses import asdict, dataclass
from typing import Any, TypeVar

from src.models._util import dict_factory

_Error = TypeVar("_Error", bound="Error")


@dataclass
class Error:
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        api_name: The api_name of this Error.
        api_version: The api_version of this Error.
        error_id: The error_id of this Error.
        error_message: The error_message of this Error.
    """

    api_name: str
    api_version: str
    error_id: str
    error_message: str

    @classmethod
    def from_dict(cls: type[_Error], input: dict[str, Any]) -> _Error:
        return cls(
            api_name=input["api_name"],
            api_version=input["api_version"],
            error_id=input["error_id"],
            error_message=input["error_message"],
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self, dict_factory=dict_factory)
