from dataclasses import asdict, dataclass
from typing import Any, Dict, Type, TypeVar

_Error = TypeVar("_Error", bound="Error")


@dataclass
class Error:
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Error - a model defined in OpenAPI

        apiName: The apiName of this Error.
        apiVersion: The apiVersion of this Error.
        errorId: The errorId of this Error.
        errorMessage: The errorMessage of this Error.
    """

    apiName: str
    apiVersion: str
    errorId: str
    errorMessage: str

    @classmethod
    def from_dict(cls: Type[_Error], input: Dict[str, Any]) -> _Error:
        return cls(
            apiName=input["apiName"],
            apiVersion=input["apiVersion"],
            errorId=input["errorId"],
            errorMessage=input["errorMessage"],
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
