from dataclasses import asdict, dataclass
from typing import Any, Dict, Type, TypeVar

_Input = TypeVar("_Input", bound="Input")


@dataclass
class Input:
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Input - a model defined in OpenAPI

        apiName: The apiName of this Input.
        name: The name of this Input.
    """

    apiName: str
    name: str

    @classmethod
    def from_dict(cls: Type[_Input], input: Dict[str, Any]) -> _Input:
        return cls(
            apiName=input["apiName"],
            name=input["name"],
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
