from dataclasses import asdict, dataclass
from typing import Any, Type, TypeVar

_Input = TypeVar("_Input", bound="Input")


@dataclass
class Input:
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Input - a model defined in OpenAPI

        api_name: The api_name of this Input.
        name: The name of this Input.
    """

    api_name: str
    name: str

    @classmethod
    def from_dict(cls: Type[_Input], input: dict[str, Any]) -> _Input:
        return cls(
            api_name=input["api_name"],
            name=input["name"],
        )

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)
