from dataclasses import asdict, dataclass
from typing import Any, Dict, Type, TypeVar

_Output = TypeVar("_Output", bound="Output")


@dataclass
class Output:
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Output - a model defined in OpenAPI

        apiName: The apiName of this Output.
        apiVersion: The apiVersion of this Output.
        text: The text of this Output.
    """

    apiName: str
    apiVersion: str
    text: str

    @classmethod
    def from_dict(cls: Type[_Output], input: Dict[str, Any]) -> _Output:
        return cls(
            apiName=input["apiName"],
            apiVersion=input["apiVersion"],
            text=input["text"],
        )

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
