name: "Apply python_template updates"
on:
  workflow_dispatch:
    inputs:
      name:
        description: "PR作成に使うブランチ名。同名のブランチが既にある場合は失敗するので注意。"
        default: "apply-template-updates"
        required: true
      pathspec:
        description: "変更適用対象のファイル。pathspec（.gitignoreで使う記法）で指定する。" # https://git-scm.com/docs/gitignore#_pattern_format
        default: "':/' ':!/src/models' ':!/src' ':!/tests'"
        required: true
jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            const CURRENT_VERSION = require('./.github/scripts/currentVersion.js')
            core.exportVariable('CURRENT_VERSION', CURRENT_VERSION)
      - run: |
          git checkout -b ${{ github.event.inputs.name }}
          ./scripts/apply_template_updates.sh
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ${{ github.event.inputs.pathspec }} ':!.github/workflows'
          git commit -m 'Apply python_template updates'
          git push --set-upstream origin ${{ github.event.inputs.name }}
          git checkout .
      - uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/scripts/createPullRequest.js')
            await script({github, context}, '${{ github.event.inputs.name }}')
