name: Run hadolint
on:
  push:
    paths:
      - .devcontainer/**Dockerfile
  pull_request_target:
    paths:
      - .devcontainer/**Dockerfile
jobs:
  devContainers:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/Dockerfile
  devContainersGpu:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/gpu.Dockerfile
