name: Run hadolint
on:
  pull_request:
    paths:
      - Dockerfile
      - .devcontainer
jobs:
  root:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  devContainers:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/Dockerfile
  devContainersGpu:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: .devcontainer/gpu.Dockerfile
